const express=require('express');
const cors=require('cors');
const bodyParser=require('body-parser');
const router=require('./router/route');
const app=express();
const PORT=process.env.PORT ||8000;
app.use(cors());
app.use(bodyParser.urlencoded({ extended:true}));
app.use(bodyParser.json());
app.use(router);
// app.use(express.json());
app.listen(PORT,(err)=>console.log('listening on port '+PORT));
